# Generated by Django 3.0.4 on 2020-03-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geet',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='geet',
            name='album',
        ),
        migrations.RemoveField(
            model_name='geet',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='geet',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='geet',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='geet',
            name='year',
        ),
        migrations.AddField(
            model_name='geet',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
