# Generated by Django 3.0.4 on 2020-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200327_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='geet',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
