# Generated by Django 3.0.4 on 2020-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_geet_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='geet',
            name='artist',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='geet',
            name='geet_logo',
            field=models.FileField(null=True, upload_to='logo/'),
        ),
    ]
