# Generated by Django 3.0.4 on 2020-04-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20200414_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geet',
            name='geet_logo',
        ),
    ]
