# Generated by Django 3.0.4 on 2020-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_geet_geet_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geet',
            name='artist',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
