# Generated by Django 3.0.4 on 2020-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20200417_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='geet',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
    ]
