# Generated by Django 3.0.4 on 2020-04-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_geet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geet',
            name='image',
        ),
    ]
